config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "qr_code", to: "pages#qr_code"
  get "map", to: "pages#map"

  resources :stamp_cards, only: [:index]

  get 'stamp_it', to: "stamp_cards#stamp_it"
  get 'create_card', to: "stamp_cards#create_card"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/opening_hour.rb
class OpeningHour < ApplicationRecord
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :stamp_cards
  has_many :opening_hours
  has_many :user_shops
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/stamp_card.rb
class StampCard < ApplicationRecord
  belongs_to :shop
  has_many :user_cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops
  has_many :user_cards
  has_many :user_shops
  has_many :stamp_cards, through: :shops
end

app/models/user_card.rb
class UserCard < ApplicationRecord
  belongs_to :user
  belongs_to :stamp_card
end

app/models/user_shop.rb
class UserShop < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard
    @user = current_user
    @cards = @user.user_cards
    @stamp_card_hashes = @cards.map do |card|
      {
        shop: card.stamp_card.shop.name,
        max: card.stamp_card.max_amount,
        actual: card.amount
      }
    end
  end

  def qr_code
    @user = current_user

    qrcode = RQRCode::QRCode.new(stamp_cards_path(@shop, customer_id: current_user.id))
    @svg = qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 6,
      standalone: true
    )
  end

  def map
    @shops = Shop.all
    # The `geocoded` scope filters only shops with coordinates
    @markers = @shops.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end
end

app/controllers/stamp_cards_controller.rb
class StampCardsController < ApplicationController
  before_action :set_customer, only: [:index]

  def index
    @stamp_cards = current_user.stamp_cards
  end

  def stamp_it
    @customer = User.find(params[:customer_id])
    @stamp_card = StampCard.find(params[:stamp_card_id])
    @user_card = UserCard.find_by(user_id: @customer.id, stamp_card_id: @stamp_card.id)
    @user_card.amount += 1
    @user_card.save
    redirect_to stamp_cards_path(current_user.stamp_cards, customer_id: @customer.id)
  end

  def create_card
  end

  private

  def set_customer
    @customer = User.find(params[:customer_id]) if params[:customer_id]
  end
end

app/controllers/user_cards_controller.rb
class UserCardsController < ApplicationController
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StampsTest</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Your Stamp Cards</h1>
<% @stamp_card_hashes.each do |hash| %>
  <div class="stamp-card">
    <h3><%= hash[:shop] %></h3>
    <p>You have <%= hash[:actual] %> / <%= hash[:max] %> stamps!</p>
    <div class="d-flex">
      <% hash[:actual].times do %>
        <div class="stamp-field stamped"></div>
      <% end %>
      <% (hash[:max]-hash[:actual]).times do %>
        <div class="stamp-field"></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/map.html.erb
<div data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  <div style="width: 100%; height: 400px;" data-map-target="smallMap"></div>

  <!-- Button trigger modal -->
  <button type="button"
          class="btn btn-primary"
          data-bs-toggle="modal"
          data-bs-target="#exampleModal"
          data-action="click->map#passPositionToModalMap">
    Launch demo modal
  </button>

  <!-- Modal -->
  <div class="modal fade"
        data-action="change->map#switchToModalMap"
        data-action="hide.bs.modal->map#switchToSmallMap"
        id="exampleModal"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div style="width: 100%; height: 600px;"
          data-map-target="modalMap"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/qr_code.html.erb
<%= @svg.html_safe %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="d-flex justify-content-between align-items-center bg-primary">
  <i class="fa-solid fa-house"></i>
  <div class="dropdown">
    <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="fa-solid fa-bars"></i>
    </button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
  </div>
</div>

app/views/stamp_cards/index.html.erb
<h1>Stamp Cards Index</h1>

<ul>
  <% @stamp_cards.each do |stamp_card| %>
    <li><%= stamp_card.discount_item %></li>
    <%= link_to "Stamp it!", stamp_it_path(stamp_card_id: stamp_card.id, customer_id: @customer.id) %>
  <% end %>
</ul>